language: go

sudo: false

go:
- 1.6

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

install: make all

script:
- make gotest
- make projectcheck

notifications:
  email: false

after_success:
- goveralls -coverprofile=coverage.txt -service=travis-ci
