language: go
sudo: false

go:
  - 1.6

install: make all

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - make gotest
  - ${PWD}/.workspace/bin/goveralls -service=travis-ci

notifications:
  email: false

# codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
